framework:
    default_locale: 'fr'
    translator:
        default_path: '%kernel.project_dir%/translations'
        enabled: true
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
    # http_client:
        # scoped_clients:
            # only requests matching scope will use these options
            # sirene.api:
                # base_uri: 'https://api.insee.fr'
                # auth_bearer: 'f00954c0-bbb8-3497-8256-524e68fe4e85'
                # headers:
                    # Accept: 'application/json'
                    # Authorization: 'Bearer f00954c0-bbb8-3497-8256-524e68fe4e85'
        
                    