knp_snappy:
    process_timeout: 20
    pdf:
        
        enabled:    true
        binary:     '%env(resolve:WKHTMLTOPDF_PATH)%'
        options:    
            - { name: 'page-size', value: 'A4' }
            - { name: 'orientation', value: 'Landscape' }
            - { name: 'margin-top', value: 10 }
            - { name: 'margin-bottom', value: 10 }
            - { name: 'margin-left', value: 10 }
            - { name: 'margin-right', value: 10 }
          
             
  
    image:
        enabled:    true
        binary:     '%env(resolve:WKHTMLTOIMAGE_PATH)%'
        options:    []
    temporary_folder: "%kernel.cache_dir%/snappy"
   