# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: "fr"
    freeLogin: '%env(FREE_LOGIN)%'
    freeKey: '%env(FREE_KEY)%'
    maintenance:
        statut: '%env(MAINTENANCE_STATUS)%'
        ipAuthorized: '%env(MAINTENANCE_IP)%'
    token_bearer: '%env(TOKEN_BEARER)%'
    uploadImageDir: 'live_loto/image_upload'
    uploadAbsoluteUploadImageDir: '%kernel.project_dir%/public/%uploadImageDir%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'
            $freeLogin: '%freeLogin%'
            $freeKey:  '%freeKey%'
            $bearerToken: '%token_bearer%'
            $uploadImageDir: '%uploadImageDir%'
            $uploadAbsoluteUploadImageDir:  '%uploadAbsoluteUploadImageDir%'
            $security: '@security.helper'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    App\EventListener\MaintenanceListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
        arguments: ['%maintenance%']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventListener\LotoLifecycleSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }
    
    App\EntityListener\LotoEventListener:
        tags:
            - {name : 'doctrine.orm.entity_listener'}
